/*
 * ColdProff — Main firmware entry point
 * MCU: STM32L010F4P6 (TSSOP-20)
 * Modem: BC65 NB-IoT Cat-NB1 (AT commands via USART2)
 * Sensors: TMP117 + ST25DV64K (shared I2C1 bus)
 *
 * This file is the application layer. Peripheral init (MX_*_Init) is
 * generated by STM32CubeMX and lives in the Core/Src/ tree alongside this file.
 *
 * Power budget (7 days):
 *   Active  : ~25 mA × 30 s × 56 cycles = ~11 mAh
 *   Sleep   : ~18 µA × 603 h            =  ~3 mAh  (boost + BC65 PSM + STM32 STOP)
 *   Total   : ~14 mAh  →  LR936 (70 mAh) gives ~5× safety margin
 */

#include "stm32l0xx_hal.h"
#include "modem.h"
#include "sensor.h"
#include "nfc.h"
#include <string.h>

/* Peripheral handles — defined here, referenced by CubeMX MSP code */
I2C_HandleTypeDef  hi2c1;
UART_HandleTypeDef huart2;
RTC_HandleTypeDef  hrtc;

#define MAX_READINGS   56       /* 7 days × 8 readings/day */
#define SLEEP_SECONDS  10800    /* 3 hours */

static CellData_t cell_data;

/* Forward declarations for CubeMX-generated init stubs */
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_I2C1_Init(void);
void MX_USART2_UART_Init(void);
void MX_RTC_Init(void);

/* ------------------------------------------------------------------ */
/* RTC wakeup: uses RTC WakeUp timer (supports up to 65535 s = ~18 h) */
/* ------------------------------------------------------------------ */
static void rtc_set_wakeup(uint32_t seconds) {
    HAL_RTCEx_DeactivateWakeUpTimer(&hrtc);
    /* CK_SPRE_16BITS = 1 Hz clock, counter = seconds - 1 */
    HAL_RTCEx_SetWakeUpTimer_IT(&hrtc, seconds - 1,
                                RTC_WAKEUPCLOCK_CK_SPRE_16BITS);
}

/* Enter STOP mode with low-power regulator. Wakes on RTC WakeUp IRQ.
 * Clocks must be reconfigured after exit (STOP kills PLL/HSI). */
static void sleep_3h(void) {
    rtc_set_wakeup(SLEEP_SECONDS);
    HAL_SuspendTick();
    HAL_PWR_EnterSTOPMode(PWR_LOWPOWERREGULATOR_ON, PWR_STOPENTRY_WFI);
    /* --- wakes here after RTC WakeUp --- */
    SystemClock_Config();   /* restore clocks (HSI16 + PLL if used) */
    HAL_ResumeTick();
    HAL_RTCEx_DeactivateWakeUpTimer(&hrtc);
}

/* Set STM32 RTC calendar from a Unix UTC timestamp (seconds since 1970). */
static void rtc_set_from_unix(uint32_t unix_ts) {
    if (unix_ts == 0) return;   /* no valid time */

    /* Days since epoch → year/month/day */
    uint32_t days = unix_ts / 86400;
    uint32_t rem  = unix_ts % 86400;

    RTC_TimeTypeDef t = {0};
    t.Hours   = rem / 3600;
    t.Minutes = (rem % 3600) / 60;
    t.Seconds = rem % 60;

    /* Year/month/day from days (Gregorian, 1970-2106 range) */
    uint32_t y = 1970;
    while (1) {
        uint32_t dy = ((y % 4 == 0) && (y % 100 != 0 || y % 400 == 0)) ? 366 : 365;
        if (days < dy) break;
        days -= dy; y++;
    }
    static const uint8_t dim[12] = {31,28,31,30,31,30,31,31,30,31,30,31};
    int leap = ((y % 4 == 0) && (y % 100 != 0 || y % 400 == 0));
    uint8_t m = 1;
    while (1) {
        uint8_t d = dim[m - 1] + (m == 2 && leap ? 1 : 0);
        if (days < d) break;
        days -= d; m++;
    }

    RTC_DateTypeDef date = {0};
    date.Year  = (uint8_t)(y - 2000);
    date.Month = m;
    date.Date  = (uint8_t)(days + 1);

    HAL_RTC_SetTime(&hrtc, &t, RTC_FORMAT_BIN);
    HAL_RTC_SetDate(&hrtc, &date, RTC_FORMAT_BIN);
}

/* Read current RTC as Unix UTC timestamp. */
static uint32_t rtc_get_unix(void) {
    RTC_TimeTypeDef t;
    RTC_DateTypeDef d;
    HAL_RTC_GetTime(&hrtc, &t, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &d, RTC_FORMAT_BIN);

    int year = 2000 + d.Year;
    static const uint8_t dim[12] = {31,28,31,30,31,30,31,31,30,31,30,31};
    uint32_t days = 0;
    for (int y = 1970; y < year; y++)
        days += ((y % 4 == 0) && (y % 100 != 0 || y % 400 == 0)) ? 366 : 365;
    int leap = ((year % 4 == 0) && (year % 100 != 0 || year % 400 == 0));
    for (int mo = 1; mo < d.Month; mo++) {
        days += dim[mo - 1];
        if (mo == 2 && leap) days++;
    }
    days += d.Date - 1;
    return days * 86400U + t.Hours * 3600U + t.Minutes * 60U + t.Seconds;
}

/* ------------------------------------------------------------------ */
int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();
    MX_RTC_Init();

    modem_init(&huart2);
    sensor_init(&hi2c1);
    if (nfc_init(&hi2c1) != 0) {
        /* NFC init failure — enter permanent low-power (nothing to do) */
        while (1) HAL_PWR_EnterSTANDBYMode();
    }

    memset(&cell_data, 0, sizeof(cell_data));

    /* First power-on: get network time and seed RTC */
    if (modem_power_on() == 0) {
        HAL_Delay(5000);    /* wait for BC65 to register (LIMSRV mode) */
        uint32_t net_ts = 0;
        modem_get_unix_time(&net_ts);
        rtc_set_from_unix(net_ts);  /* zero is a no-op */
        modem_enter_psm(SLEEP_SECONDS);
        modem_power_off();
    }

    /* Main measurement loop — 56 cycles ≈ 7 days */
    while (cell_data.measurement_count < MAX_READINGS) {

        /* Wake BC65 from PSM */
        if (modem_power_on() != 0) goto next_sleep;

        HAL_Delay(3000);    /* allow BC65 to re-acquire cell */

        /* Try network time first; fall back to STM32 RTC */
        uint32_t net_ts = 0;
        modem_get_unix_time(&net_ts);
        if (net_ts != 0) {
            rtc_set_from_unix(net_ts);
            cell_data.timestamp = net_ts;
        } else {
            cell_data.timestamp = rtc_get_unix();   /* STM32 RTC fallback */
        }

        modem_read_serving_cell(&cell_data);
        sensor_read_temp(&cell_data.temp_raw);
        nfc_write_record(&cell_data);
        cell_data.measurement_count++;

        modem_enter_psm(SLEEP_SECONDS);
        modem_power_off();

next_sleep:
        sleep_3h();     /* STM32 enters STOP for 3 h, wakes via RTC */
    }

    /* 7 days complete — final standby */
    while (1) HAL_PWR_EnterSTANDBYMode();
}

/* RTC WakeUp IRQ handler — called by stm32l0xx_it.c */
void HAL_RTCEx_WakeUpTimerEventCallback(RTC_HandleTypeDef *hrtc_cb) {
    (void)hrtc_cb;
    /* Nothing to do here — HAL exits STOP mode automatically */
}
